# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-20 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('point', '0002_auto_20171020_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('pointer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_for_invite', to='point.Pointer')),
            ],
            options={
                'ordering': ['pointer'],
            },
        ),
    ]
