# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-16 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0002_invite_to_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
