# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-02 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default=b'media/default_avatar.png', upload_to=b'media/avatars'),
        ),
    ]
