# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-07 08:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='descriptino',
            new_name='description',
        ),
    ]
