# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-10 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170510_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default=b'', max_length=130),
        ),
    ]
