# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-24 10:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170510_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_key',
            field=models.CharField(default=datetime.datetime(2017, 7, 24, 10, 48, 2, 881292, tzinfo=utc), max_length=17, unique=True),
            preserve_default=False,
        ),
    ]
