# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 18:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_auto_20170706_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendship',
            old_name='userid1',
            new_name='from_user',
        ),
        migrations.RenameField(
            model_name='friendship',
            old_name='userid2',
            new_name='to_user',
        ),
    ]
