# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-20 17:24
from __future__ import unicode_literals
from django.conf import settings

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('point', '0002_auto_20171020_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(b'Going', b'Going'), (b'Waiting', b'Waiting'), (b'Decline', b'Decline')], default=b'Going', max_length=7)),
                ('pointer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_for_member', to='point.Pointer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
            },
        ),
    ]
