# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-02 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(b'Going', b'Going'), (b'Waiting', b'Waiting'), (b'Decline', b'Decline')], default=b'Going', max_length=7)),
            ],
            options={
                'ordering': ['user'],
            },
        ),
    ]
