# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-21 15:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('point', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(b'Going', b'Going'), (b'Waiting', b'Waiting'), (b'Decline', b'Decline')], default=b'Going', max_length=7)),
                ('pointer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_for_member', to='point.Pointer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
            },
        ),
    ]
