# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-02 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('point', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='pointer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_for_member', to='point.Pointer'),
        ),
    ]
