# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-17 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20171017_1907'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={},
        ),
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[(b'Pointed', 'Pointed'), (b'Waiting', 'Waiting'), (b'Decline', 'Decline')], default=b'Waiting', max_length=7),
        ),
        migrations.AlterField(
            model_name='member',
            name='pointer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='point.Pointer'),
        ),
    ]
