# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-20 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('Going', 'Going'), ('Waiting', 'Waiting'), ('Decline', 'Decline')], default='Going', max_length=7),
        ),
    ]
