# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-19 17:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20171017_2000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['user']},
        ),
        migrations.AlterField(
            model_name='member',
            name='pointer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='point.Pointer'),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[(b'Going', b'Going'), (b'Waiting', b'Waiting'), (b'Decline', b'Decline')], default=b'Going', max_length=7),
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL),
        ),
    ]
